// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type DashboardAppProps struct{}

func DashboardApp(props DashboardAppProps) gf.Node {
	issues, setIssues := gf.UseState(resetDemoIssues())
	query, setQuery := gf.UseState("")
	statusFilter, setStatusFilter := gf.UseState(StatusAll)
	priorityFilter, setPriorityFilter := gf.UseState(PriorityAll)
	sortMode, setSortMode := gf.UseState(SortByUpdated)
	selectedID, setSelectedID := gf.UseState(0)

	filters := FilterState{
		Query:    query,
		Status:   statusFilter,
		Priority: priorityFilter,
		Sort:     sortMode,
	}
	visible := visibleIssues(issues, filters)
	metrics := dashboardMetrics(issues, len(visible))
	selectedIssue, selectedFound := findIssue(issues, selectedID)

	gf.UseEffect(func() gf.Cleanup {
		setDocumentTitle("GoFrame Dashboard · " + gf.ToString(len(visible)) + " visible")
		return nil
	}, gf.Deps(len(visible)))

	reset := func() {
		setIssues(resetDemoIssues())
		setQuery("")
		setStatusFilter(StatusAll)
		setPriorityFilter(PriorityAll)
		setSortMode(SortByUpdated)
		setSelectedID(0)
	}

	toggleIssue := func(id int) {
		setIssues(toggleIssueStatus(issues, id))
	}

	simulateUpdate := func() {
		setIssues(simulateIssueUpdate(issues))
	}

	return gf.Component("DashboardShell", DashboardShellProps{
		Children: []gf.Node{
			gf.Component("MetricsGrid", MetricsGridProps{
				Metrics: metrics,
			}, MetricsGrid),
			gf.Component("Card", CardProps{
				Title:  "Filters",
				TestID: "filters-card",
				Children: []gf.Node{
					gf.Component("FilterBar", FilterBarProps{
						Filters:    filters,
						OnQuery:    setQuery,
						OnStatus:   setStatusFilter,
						OnPriority: setPriorityFilter,
						OnSort:     setSortMode,
						OnReset:    reset,
						OnSimulate: simulateUpdate,
					}, FilterBar),
				},
			}, Card),
			gf.El("div", gf.Props{
				"class": "content-grid",
			},
				gf.Component("Card", CardProps{
					Title:  "Issues",
					TestID: "issues-card",
					Children: []gf.Node{
						gf.El("p", gf.Props{
							"class":       "summary",
							"data-testid": "visible-summary",
						},
							gf.Child(summaryText(len(visible), len(issues))),
						),
						gf.IfElse(len(visible) == 0, gf.Component("EmptyState", EmptyStateProps{
							Query: query,
						}, EmptyState), gf.Component("IssueTable", IssueTableProps{
							Items:      visible,
							SelectedID: selectedID,
							OnSelect:   setSelectedID,
							OnToggle:   toggleIssue,
						}, IssueTable)),
					},
				}, Card),
				gf.Component("DetailPanel", DetailPanelProps{
					Issue:    selectedIssue,
					Found:    selectedFound,
					OnToggle: toggleIssue,
				}, DetailPanel),
			),
		},
	}, DashboardShell)
}

func App() gf.Node {
	return gf.Fragment(
		gf.Component("Header", HeaderProps{
			Title:    "Operations Dashboard",
			Subtitle: "A dashboard-sized GOX pressure test with filters, keyed rows, and derived views.",
		}, Header),
		gf.Component("DashboardApp", DashboardAppProps{}, DashboardApp),
	)
}
