// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type HeaderProps struct {
	Title    string
	Subtitle string
}

func Header(props HeaderProps) gf.Node {
	return gf.El("header", gf.Props{
		"class":       "site-header",
		"data-testid": "dashboard-header",
	},
		gf.El("p", gf.Props{
			"class": "eyebrow",
		},
			gf.Text("GoFrame pressure test"),
		),
		gf.El("h1", nil,
			gf.Child(props.Title),
		),
		gf.El("p", nil,
			gf.Child(props.Subtitle),
		),
	)
}

type DashboardShellProps struct {
	Children []gf.Node
}

func DashboardShell(props DashboardShellProps) gf.Node {
	return gf.El("main", gf.Props{
		"class":       "dashboard-shell",
		"data-testid": "dashboard-shell",
	},
		gf.Child(props.Children),
	)
}

type CardProps struct {
	Title    string
	TestID   string
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", gf.Props{
		"class":       "card",
		"data-testid": props.TestID,
	},
		gf.El("h2", nil,
			gf.Child(props.Title),
		),
		gf.El("div", gf.Props{
			"class": "card-body",
		},
			gf.Child(props.Children),
		),
	)
}

type ButtonProps struct {
	Label   string
	Kind    string
	OnClick func()
}

func Button(props ButtonProps) gf.Node {
	className := "button"
	if props.Kind != "" {
		className += " button-" + props.Kind
	}
	return gf.El("button", gf.Props{
		"class":   className,
		"Type":    "button",
		"OnClick": props.OnClick,
	},
		gf.Child(props.Label),
	)
}
