// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type SearchBoxProps struct {
	Query    string
	OnChange func(value string)
}

func SearchBox(props SearchBoxProps) gf.Node {
	return gf.El("label", gf.Props{
		"class": "field search-field",
	},
		gf.El("span", nil,
			gf.Text("Search"),
		),
		gf.El("input", gf.Props{
			"ID":          "dashboard-search",
			"Type":        "search",
			"Value":       props.Query,
			"Placeholder": "Search title, owner, or service",
			"OnInput": func(event gf.InputEvent) {
				props.OnChange(event.Value())
			},
		},
		),
	)
}

type FilterBarProps struct {
	Filters    FilterState
	OnQuery    func(value string)
	OnStatus   func(value Status)
	OnPriority func(value Priority)
	OnSort     func(value SortMode)
	OnReset    func()
	OnSimulate func()
}

func FilterBar(props FilterBarProps) gf.Node {
	return gf.El("div", gf.Props{
		"class":       "filter-bar",
		"data-testid": "filter-bar",
	},
		gf.Component("SearchBox", SearchBoxProps{
			Query:    props.Filters.Query,
			OnChange: props.OnQuery,
		}, SearchBox),
		gf.El("label", gf.Props{
			"class": "field",
		},
			gf.El("span", nil,
				gf.Text("Status"),
			),
			gf.El("select", gf.Props{
				"ID":    "status-filter",
				"Value": props.Filters.Status,
				"OnChange": func(event gf.InputEvent) {
					props.OnStatus(Status(event.Value()))
				},
			},
				gf.El("option", gf.Props{
					"Value": StatusAll,
				},
					gf.Child(statusLabel(StatusAll)),
				),
				gf.El("option", gf.Props{
					"Value": StatusOpen,
				},
					gf.Child(statusLabel(StatusOpen)),
				),
				gf.El("option", gf.Props{
					"Value": StatusInProgress,
				},
					gf.Child(statusLabel(StatusInProgress)),
				),
				gf.El("option", gf.Props{
					"Value": StatusBlocked,
				},
					gf.Child(statusLabel(StatusBlocked)),
				),
				gf.El("option", gf.Props{
					"Value": StatusResolved,
				},
					gf.Child(statusLabel(StatusResolved)),
				),
			),
		),
		gf.El("label", gf.Props{
			"class": "field",
		},
			gf.El("span", nil,
				gf.Text("Priority"),
			),
			gf.El("select", gf.Props{
				"ID":    "priority-filter",
				"Value": props.Filters.Priority,
				"OnChange": func(event gf.InputEvent) {
					props.OnPriority(Priority(event.Value()))
				},
			},
				gf.El("option", gf.Props{
					"Value": PriorityAll,
				},
					gf.Child(priorityLabel(PriorityAll)),
				),
				gf.El("option", gf.Props{
					"Value": PriorityLow,
				},
					gf.Child(priorityLabel(PriorityLow)),
				),
				gf.El("option", gf.Props{
					"Value": PriorityMedium,
				},
					gf.Child(priorityLabel(PriorityMedium)),
				),
				gf.El("option", gf.Props{
					"Value": PriorityHigh,
				},
					gf.Child(priorityLabel(PriorityHigh)),
				),
				gf.El("option", gf.Props{
					"Value": PriorityCritical,
				},
					gf.Child(priorityLabel(PriorityCritical)),
				),
			),
		),
		gf.El("label", gf.Props{
			"class": "field",
		},
			gf.El("span", nil,
				gf.Text("Sort"),
			),
			gf.El("select", gf.Props{
				"ID":    "sort-mode",
				"Value": props.Filters.Sort,
				"OnChange": func(event gf.InputEvent) {
					props.OnSort(SortMode(event.Value()))
				},
			},
				gf.El("option", gf.Props{
					"Value": SortByUpdated,
				},
					gf.Child(sortLabel(SortByUpdated)),
				),
				gf.El("option", gf.Props{
					"Value": SortByPriority,
				},
					gf.Child(sortLabel(SortByPriority)),
				),
				gf.El("option", gf.Props{
					"Value": SortByEvents,
				},
					gf.Child(sortLabel(SortByEvents)),
				),
				gf.El("option", gf.Props{
					"Value": SortByOwner,
				},
					gf.Child(sortLabel(SortByOwner)),
				),
			),
		),
		gf.El("div", gf.Props{
			"class": "filter-actions",
		},
			gf.Component("Button", ButtonProps{
				Label:   "Simulate update",
				Kind:    "secondary",
				OnClick: props.OnSimulate,
			}, Button),
			gf.Component("Button", ButtonProps{
				Label:   "Reset",
				Kind:    "ghost",
				OnClick: props.OnReset,
			}, Button),
		),
	)
}
