// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type MetricCardProps struct {
	Label string
	Value int
	Tone  string
}

func MetricCard(props MetricCardProps) gf.Node {
	className := "metric-card"
	if props.Tone != "" {
		className += " metric-" + props.Tone
	}
	return gf.El("div", gf.Props{
		"class": className,
	},
		gf.El("span", nil,
			gf.Child(props.Label),
		),
		gf.El("strong", nil,
			gf.Child(props.Value),
		),
	)
}

type MetricsGridProps struct {
	Metrics Metrics
}

func MetricsGrid(props MetricsGridProps) gf.Node {
	return gf.El("div", gf.Props{
		"class":       "metrics-grid",
		"data-testid": "metrics-grid",
	},
		gf.Component("MetricCard", MetricCardProps{
			Label: "Total",
			Value: props.Metrics.Total,
			Tone:  "neutral",
		}, MetricCard),
		gf.Component("MetricCard", MetricCardProps{
			Label: "Visible",
			Value: props.Metrics.Visible,
			Tone:  "active",
		}, MetricCard),
		gf.Component("MetricCard", MetricCardProps{
			Label: "Open",
			Value: props.Metrics.Open,
			Tone:  "open",
		}, MetricCard),
		gf.Component("MetricCard", MetricCardProps{
			Label: "Blocked",
			Value: props.Metrics.Blocked,
			Tone:  "blocked",
		}, MetricCard),
		gf.Component("MetricCard", MetricCardProps{
			Label: "Critical",
			Value: props.Metrics.Critical,
			Tone:  "critical",
		}, MetricCard),
		gf.Component("MetricCard", MetricCardProps{
			Label: "Events",
			Value: props.Metrics.EventCount,
			Tone:  "events",
		}, MetricCard),
	)
}
