// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type IssueTableProps struct {
	Items      []Issue
	SelectedID int
	OnSelect   func(id int)
	OnToggle   func(id int)
}

func IssueTable(props IssueTableProps) gf.Node {
	return gf.El("table", gf.Props{
		"class":       "issue-table",
		"data-testid": "issue-table",
	},
		gf.El("thead", nil,
			gf.El("tr", nil,
				gf.El("th", nil,
					gf.Text("Issue"),
				),
				gf.El("th", nil,
					gf.Text("Status"),
				),
				gf.El("th", nil,
					gf.Text("Priority"),
				),
				gf.El("th", nil,
					gf.Text("Owner"),
				),
				gf.El("th", nil,
					gf.Text("Service"),
				),
				gf.El("th", nil,
					gf.Text("Events"),
				),
				gf.El("th", nil,
					gf.Text("Action"),
				),
			),
		),
		gf.El("tbody", nil,
			gf.Child(gf.Map(props.Items, func(issue Issue) gf.Node {
				return gf.Key(gf.ToString(issue.ID),
					gf.Component("IssueRow", IssueRowProps{
						Issue:    issue,
						Selected: issue.ID == props.SelectedID,
						OnSelect: props.OnSelect,
						OnToggle: props.OnToggle,
					}, IssueRow),
				)
			})),
		),
	)
}

type IssueRowProps struct {
	Issue    Issue
	Selected bool
	OnSelect func(id int)
	OnToggle func(id int)
}

func IssueRow(props IssueRowProps) gf.Node {
	className := "issue-row"
	if props.Selected {
		className += " issue-row-selected"
	}
	return gf.El("tr", gf.Props{
		"ID":          "issue-row-" + gf.ToString(props.Issue.ID),
		"class":       className,
		"data-testid": "issue-row-" + gf.ToString(props.Issue.ID),
	},
		gf.El("td", nil,
			gf.El("button", gf.Props{
				"class": "row-link",
				"Type":  "button",
				"OnClick": func() {
					props.OnSelect(props.Issue.ID)
				},
			},
				gf.El("span", gf.Props{
					"class": "issue-id",
				},
					gf.Text("#"),
					gf.Child(props.Issue.ID),
				),
				gf.El("span", nil,
					gf.Child(props.Issue.Title),
				),
			),
		),
		gf.El("td", nil,
			gf.El("span", gf.Props{
				"class": statusClass(props.Issue.Status),
			},
				gf.Child(statusLabel(props.Issue.Status)),
			),
		),
		gf.El("td", nil,
			gf.El("span", gf.Props{
				"class": priorityClass(props.Issue.Priority),
			},
				gf.Child(priorityLabel(props.Issue.Priority)),
			),
		),
		gf.El("td", nil,
			gf.Child(props.Issue.Owner),
		),
		gf.El("td", nil,
			gf.Child(props.Issue.Service),
		),
		gf.El("td", nil,
			gf.Child(props.Issue.Events),
		),
		gf.El("td", nil,
			gf.Component("Button", ButtonProps{
				Label: "Toggle",
				Kind:  "tiny",
				OnClick: func() {
					props.OnToggle(props.Issue.ID)
				},
			}, Button),
		),
	)
}

type EmptyStateProps struct {
	Query string
}

func EmptyState(props EmptyStateProps) gf.Node {
	return gf.El("div", gf.Props{
		"class":       "empty-state",
		"data-testid": "dashboard-empty",
	},
		gf.El("strong", nil,
			gf.Text("No issues match the current filters."),
		),
		gf.If((props.Query != ""), gf.El("span", nil,
			gf.Text("Try clearing search for \""),
			gf.Child(props.Query),
			gf.Text("\"."),
		)),
	)
}
