// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type DetailPanelProps struct {
	Issue    Issue
	Found    bool
	OnToggle func(id int)
}

func DetailPanel(props DetailPanelProps) gf.Node {
	return gf.El("aside", gf.Props{
		"class":       "detail-panel",
		"data-testid": "detail-panel",
	},
		gf.IfElse(props.Found, gf.El("div", nil,
			gf.El("p", gf.Props{
				"class": "eyebrow",
			},
				gf.Text("Selected issue"),
			),
			gf.El("h2", nil,
				gf.Child(props.Issue.Title),
			),
			gf.El("dl", gf.Props{
				"class": "detail-list",
			},
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("ID"),
					),
					gf.El("dd", nil,
						gf.Text("#"),
						gf.Child(props.Issue.ID),
					),
				),
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("Status"),
					),
					gf.El("dd", nil,
						gf.Child(statusLabel(props.Issue.Status)),
					),
				),
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("Priority"),
					),
					gf.El("dd", nil,
						gf.Child(priorityLabel(props.Issue.Priority)),
					),
				),
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("Owner"),
					),
					gf.El("dd", nil,
						gf.Child(props.Issue.Owner),
					),
				),
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("Service"),
					),
					gf.El("dd", nil,
						gf.Child(props.Issue.Service),
					),
				),
				gf.El("div", nil,
					gf.El("dt", nil,
						gf.Text("Events"),
					),
					gf.El("dd", nil,
						gf.Child(props.Issue.Events),
					),
				),
			),
			gf.Component("Button", ButtonProps{
				Label: "Toggle resolved",
				Kind:  "secondary",
				OnClick: func() {
					props.OnToggle(props.Issue.ID)
				},
			}, Button),
		), gf.Component("EmptyDetail", EmptyDetailProps{}, EmptyDetail)),
	)
}

type EmptyDetailProps struct{}

func EmptyDetail(props EmptyDetailProps) gf.Node {
	return gf.El("div", gf.Props{
		"class": "empty-detail",
	},
		gf.El("p", gf.Props{
			"class": "eyebrow",
		},
			gf.Text("Selected issue"),
		),
		gf.El("h2", nil,
			gf.Text("No issue selected"),
		),
		gf.El("p", nil,
			gf.Text("Select a row to inspect current status, owner, service, and event volume."),
		),
	)
}
