// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

func App() gf.Node {
	count, setCount := gf.UseState(0)

	return gf.El("div", gf.Props{
		"class": "app",
	},
		gf.El("h1", nil,
			gf.Text("Counter: "),
			gf.Child(count),
		),
		gf.El("button", gf.Props{
			"onClick": func() {
				setCount(count + 1)
			},
		},
			gf.Text("Increment"),
		),
	)
}
