// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

type CardProps struct {
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", nil,
		gf.Child(props.Children),
	)
}

func View(show bool) gf.Node {
	return gf.Component("Card", CardProps{
		Children: []gf.Node{
			gf.Child(gf.If(show, gf.Text("Visible"))),
		},
	}, Card)
}
