// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_component_children_Card = gf.NewComponentType("demo.Card", "Card")
)

type CardProps struct {
	Title    string
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", nil,
		gf.El("h2", nil,
			gf.Child(props.Title),
		),
		gf.El("div", nil,
			gf.Child(props.Children),
		),
	)
}

func View() gf.Node {
	return gf.ComponentT(_goxComponent_component_children_Card, CardProps{
		Title: "Stats",
		Children: []gf.Node{
			gf.El("p", nil,
				gf.Text("Counter: "),
				gf.Child(1),
			),
		},
	}, Card)
}
