// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

type ButtonProps struct {
	Label   string
	OnClick func()
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", gf.Props{
		"onClick": props.OnClick,
	},
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.Component("Button", ButtonProps{
		Label:   "Increment",
		OnClick: func() {},
	}, Button)
}
