// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_component_props_Button = gf.NewComponentType("demo.Button", "Button")
)

type ButtonProps struct {
	Label   string
	OnClick func()
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", gf.Props{
		"onClick": props.OnClick,
	},
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.ComponentT(_goxComponent_component_props_Button, ButtonProps{
		Label:   "Increment",
		OnClick: func() {},
	}, Button)
}
