// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

func View(show bool, ready bool, active bool) gf.Node {
	return gf.El("main", nil,
		gf.If(show, gf.El("p", nil,
			gf.Text("Shown"),
		)),
		gf.If((ready && active), gf.Fragment(
			gf.El("span", nil,
				gf.Text("Ready"),
			),
		)),
		gf.Child(ready && active),
	)
}
