// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

func View(items []int) gf.Node {
	return gf.El("main", nil,
		gf.If((len(items) > 0), gf.El("p", gf.Props{
			"class": "summary",
		},
			gf.Child(len(items)),
			gf.Text(" item(s)"),
		)),
	)
}
