// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

func View(show bool) gf.Node {
	return gf.El("main", nil,
		gf.Child(gf.If(show, gf.Text("Visible"))),
		gf.Child(gf.IfElse(show, gf.Text("On"), gf.Text("Off"))),
	)
}
