// Code generated by goxc; DO NOT EDIT.

package demo

import (
	pages "github.com/example/app/internal/pages"
	gf "github.com/graybuton/goframe/pkg/goframe"
)

var (
	_goxComponent_error_boundary_gf_ErrorBoundary = gf.NewComponentType("github.com/graybuton/goframe/pkg/goframe.ErrorBoundary", "gf.ErrorBoundary")
	_goxComponent_error_boundary_pages_Risky      = gf.NewComponentType("github.com/example/app/internal/pages.Risky", "pages.Risky")
)

func View(routeKey string, fallback func(gf.ErrorBoundaryContext) gf.Node) gf.Node {
	return gf.ComponentT(_goxComponent_error_boundary_gf_ErrorBoundary, gf.ErrorBoundaryProps{
		ResetKey: routeKey,
		Fallback: fallback,
		Children: []gf.Node{
			gf.ComponentT(_goxComponent_error_boundary_pages_Risky, pages.RiskyProps{}, pages.Risky),
		},
	}, gf.ErrorBoundary)
}
