// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

func View() gf.Node {
	return gf.Fragment(
		gf.El("h1", nil,
			gf.Text("Hello"),
		),
		gf.El("p", nil,
			gf.Text("World"),
		),
	)
}
