// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

func View(value string, update func(string)) gf.Node {
	return gf.El("input", gf.Props{
		"Type":        "text",
		"Value":       value,
		"Placeholder": "New task",
		"OnInput": func(event gf.InputEvent) {
			update(event.Value())
		},
	},
	)
}
