// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/jin-wu/goframe/pkg/goframe"

type RowProps struct {
	Label string
}

func Row(props RowProps) gf.Node {
	return gf.El("li", nil,
		gf.Child(props.Label),
	)
}

func View(id int, label string) gf.Node {
	return gf.El("ul", nil,
		gf.Key(gf.ToString(id),
			gf.El("li", nil,
				gf.Child(label),
			),
		),
		gf.Key("static-row",
			gf.Component("Row", RowProps{
				Label: label,
			}, Row),
		),
	)
}
