// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_key_pseudo_props_Row = gf.NewComponentType("main.Row", "Row")
)

type RowProps struct {
	Label string
}

func Row(props RowProps) gf.Node {
	return gf.El("li", nil,
		gf.Child(props.Label),
	)
}

func View(id int, label string) gf.Node {
	return gf.El("ul", nil,
		gf.Key(gf.ToString(id),
			gf.El("li", nil,
				gf.Child(label),
			),
		),
		gf.Key("static-row",
			gf.ComponentT(_goxComponent_key_pseudo_props_Row, RowProps{
				Label: label,
			}, Row),
		),
	)
}
