// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

type ItemProps struct {
	Label string
}

func Item(props ItemProps) gf.Node {
	return gf.El("li", nil,
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.Key("item-1", gf.Component("Item", ItemProps{
		Label: "One",
	}, Item))
}
