// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_keyed_component_Item = gf.NewComponentType("demo.Item", "Item")
)

type ItemProps struct {
	Label string
}

func Item(props ItemProps) gf.Node {
	return gf.El("li", nil,
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.Key("item-1", gf.ComponentT(_goxComponent_keyed_component_Item, ItemProps{
		Label: "One",
	}, Item))
}
