// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

func View(items []string) gf.Node {
	return gf.El("ul", nil,
		gf.Child(gf.ForIndexed(items, func(index int, item string) gf.Node {
			return gf.Key(gf.ToString(index), gf.El("li", nil, gf.Text(item)))
		})),
	)
}
