// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

func View(items []string) gf.Node {
	return gf.El("ul", nil,
		gf.Child(gf.For(items, func(item string) gf.Node {
			return gf.El("li", nil, gf.Text(item))
		})),
	)
}
