// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

type Item struct {
	ID     int
	Label  string
	Hidden bool
}

type ItemRowProps struct {
	Item Item
}

func ItemRow(props ItemRowProps) gf.Node {
	return gf.El("li", nil,
		gf.Child(props.Item.Label),
	)
}

func View(items []Item) gf.Node {
	return gf.El("ul", nil,
		gf.Child(gf.Map(items, func(item Item) gf.Node {
			if item.Hidden {
				return gf.Fragment()
			}
			return gf.Key(gf.ToString(item.ID),
				gf.Component("ItemRow", ItemRowProps{
					Item: item,
				}, ItemRow),
			)
		})),
	)
}
