// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_nested_components_Card   = gf.NewComponentType("demo.Card", "Card")
	_goxComponent_nested_components_Button = gf.NewComponentType("demo.Button", "Button")
)

type CardProps struct {
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", nil,
		gf.Child(props.Children),
	)
}

type ButtonProps struct {
	Label string
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", nil,
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.ComponentT(_goxComponent_nested_components_Card, CardProps{
		Children: []gf.Node{
			gf.ComponentT(_goxComponent_nested_components_Button, ButtonProps{
				Label: "Nested",
			}, Button),
		},
	}, Card)
}
