// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

type CardProps struct {
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", nil,
		gf.Child(props.Children),
	)
}

type ButtonProps struct {
	Label string
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", nil,
		gf.Child(props.Label),
	)
}

func View() gf.Node {
	return gf.Component("Card", CardProps{
		Children: []gf.Node{
			gf.Component("Button", ButtonProps{
				Label: "Nested",
			}, Button),
		},
	}, Card)
}
