// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

func View(count int) gf.Node {
	return gf.El("p", nil,
		gf.Child(count),
		gf.Text(" item(s)"),
	)
}
