// Code generated by goxc; DO NOT EDIT.

package demo

import (
	rows "github.com/example/app/internal/rows"
	ui "github.com/example/app/internal/ui"
	gf "github.com/graybuton/goframe/pkg/goframe"
)

var (
	_goxComponent_package_qualified_component_ui_Shell      = gf.NewComponentType("github.com/example/app/internal/ui.Shell", "ui.Shell")
	_goxComponent_package_qualified_component_gf_RouterLink = gf.NewComponentType("github.com/graybuton/goframe/pkg/goframe.RouterLink", "gf.RouterLink")
	_goxComponent_package_qualified_component_rows_ItemRow  = gf.NewComponentType("github.com/example/app/internal/rows.ItemRow", "rows.ItemRow")
)

type Item struct {
	ID string
}

func View(items []Item) gf.Node {
	return gf.ComponentT(_goxComponent_package_qualified_component_ui_Shell, ui.ShellProps{
		Title: "Dashboard",
		Children: []gf.Node{
			gf.ComponentT(_goxComponent_package_qualified_component_gf_RouterLink, gf.RouterLinkProps{
				To:    "/issues",
				Class: "link",
				Children: []gf.Node{
					gf.Text("Issues"),
				},
			}, gf.RouterLink),
			gf.El("ul", nil,
				gf.Child(gf.Map(items, func(item Item) gf.Node {
					return gf.Key(gf.ToString(item.ID),
						gf.ComponentT(_goxComponent_package_qualified_component_rows_ItemRow, rows.ItemRowProps{
							Item: item,
						}, rows.ItemRow),
					)
				})),
			),
		},
	}, ui.Shell)
}
