// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

func View() gf.Node {
	return gf.El("main", gf.Props{
		"class": "page",
	},
		gf.El("input", gf.Props{
			"type": "text",
		},
		),
		gf.El("br", nil),
		gf.El("p", nil,
			gf.Text("Hello "),
			gf.Child(42),
		),
	)
}
