// Code generated by goxc; DO NOT EDIT.

package demo

import gf "github.com/jin-wu/goframe/pkg/goframe"

func View(condition bool, count int) gf.Node {
	return gf.El("section", nil,
		gf.IfElse(condition, gf.El("p", nil,
			gf.Child(count),
			gf.Text(" item(s)"),
		), gf.El("p", nil,
			gf.Text("empty"),
		)),
	)
}
