// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/graybuton/goframe/pkg/goframe"

var (
	_goxComponent_ternary_render_Empty = gf.NewComponentType("main.Empty", "Empty")
	_goxComponent_ternary_render_List  = gf.NewComponentType("main.List", "List")
)

type EmptyProps struct{}

func Empty(props EmptyProps) gf.Node {
	return gf.El("p", nil,
		gf.Text("Empty"),
	)
}

type ListProps struct {
	Items []string
}

func List(props ListProps) gf.Node {
	return gf.El("ul", nil)
}

func View(items []string) gf.Node {
	return gf.El("section", nil,
		gf.IfElse(len(items) == 0, gf.ComponentT(_goxComponent_ternary_render_Empty, EmptyProps{}, Empty), gf.ComponentT(_goxComponent_ternary_render_List, ListProps{
			Items: items,
		}, List)),
	)
}
