// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/jin-wu/goframe/pkg/goframe"

type EmptyProps struct{}

func Empty(props EmptyProps) gf.Node {
	return gf.El("p", nil,
		gf.Text("Empty"),
	)
}

type ListProps struct {
	Items []string
}

func List(props ListProps) gf.Node {
	return gf.El("ul", nil)
}

func View(items []string) gf.Node {
	return gf.El("section", nil,
		gf.IfElse(len(items) == 0, gf.Component("Empty", EmptyProps{}, Empty), gf.Component("List", ListProps{
			Items: items,
		}, List)),
	)
}
