package gox

import (
	"bytes"
	"fmt"
	"go/format"
	"go/parser"
	gotoken "go/token"
	"os"
	pathpkg "path"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
)

const generatedHeader = "// Code generated by goxc; DO NOT EDIT.\n\n"

// GenerateOptions configures GOX generation.
type GenerateOptions struct {
	// Filename is used in diagnostics and generated component variable names.
	Filename string
	// PackageIdentity is the component identity prefix for generated component
	// types. When empty, generation falls back to the Go package name from the
	// source file.
	PackageIdentity string
}

// Generate transpiles all GOX element roots in a Go-like source file.
func Generate(source []byte) ([]byte, error) {
	return GenerateNamed("gox", source)
}

// GenerateNamed transpiles GOX source and includes filename in diagnostics.
func GenerateNamed(filename string, source []byte) ([]byte, error) {
	return GenerateWithOptions(source, GenerateOptions{Filename: filename})
}

// GenerateWithOptions transpiles GOX source using explicit generation options.
func GenerateWithOptions(source []byte, options GenerateOptions) ([]byte, error) {
	if options.Filename == "" {
		options.Filename = "gox"
	}
	input := string(source)
	componentIdentity := options.PackageIdentity
	if componentIdentity == "" {
		componentIdentity = packageNameFromSource(input)
	}
	ctx := newCodegenContext(componentIdentity, options.Filename, true)
	aliases, invalidAliases := importAliasesFromSource(options.Filename, input)
	ctx.withImportAliases(aliases, invalidAliases)
	var output bytes.Buffer
	cursor := 0
	searchFrom := 0
	generated := 0

	for {
		start := findMarkupStart(input, searchFrom)
		if start < 0 {
			break
		}

		line, column := lineColumn(input, start)
		element, consumed, positions, err := parseElementAtWithPositions(input[start:], options.Filename, line, column)
		if err != nil {
			return nil, err
		}
		ctx.withDiagnostics(options.Filename, input[start:], line, column, positions)
		code, err := ctx.codegen(element)
		if err != nil {
			if _, ok := asDiagnosticError(err); ok {
				return nil, err
			}
			return nil, diagnosticError(options.Filename, line, column, err.Error(), sourceLine(input, start))
		}

		replaceStart, replaceEnd := unwrapReturnParentheses(input, start, start+consumed)
		output.WriteString(input[cursor:replaceStart])
		output.WriteString(code)
		cursor = replaceEnd
		searchFrom = replaceEnd
		generated++
	}
	output.WriteString(input[cursor:])
	generatedSource := output.String()
	if declarations := ctx.declarations(); declarations != "" {
		generatedSource = insertGeneratedDeclarations(generatedSource, declarations)
	}

	if generated == 0 {
		return nil, fmt.Errorf("%s: no GOX markup elements found", options.Filename)
	}

	formatted, err := format.Source(append([]byte(generatedHeader), []byte(generatedSource)...))
	if err != nil {
		return nil, fmt.Errorf("%s: generated Go source is invalid: %w", options.Filename, err)
	}
	return formatted, nil
}

// GenerateFile writes a .gox.go file next to the source .gox file.
func GenerateFile(path string) (string, error) {
	outputPath := path + ".go"
	return GenerateFileTo(path, outputPath)
}

// GenerateFileTo writes generated Go for a .gox file to outputPath.
func GenerateFileTo(path, outputPath string) (string, error) {
	return GenerateFileToWithOptions(path, outputPath, GenerateOptions{Filename: path})
}

// GenerateFileToWithOptions writes generated Go for a .gox file to outputPath.
func GenerateFileToWithOptions(path, outputPath string, options GenerateOptions) (string, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if options.Filename == "" {
		options.Filename = path
	}
	generated, err := GenerateWithOptions(source, options)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", fmt.Errorf("create generated directory for %s: %w", outputPath, err)
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", outputPath, err)
	}
	return outputPath, nil
}

// FindFiles returns .gox files below path in stable order.
func FindFiles(path string) ([]string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		if filepath.Ext(path) != ".gox" {
			return nil, fmt.Errorf("%s is not a .gox file", path)
		}
		return []string{path}, nil
	}

	var files []string
	err = filepath.WalkDir(path, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && filepath.Ext(path) == ".gox" {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

func findMarkupStart(input string, from int) int {
	for index := from; index < len(input); {
		switch {
		case input[index] == '"' || input[index] == '\'' || input[index] == '`':
			index = skipGoQuoted(input, index)
		case strings.HasPrefix(input[index:], "//"):
			index += 2
			for index < len(input) && input[index] != '\n' {
				index++
			}
		case strings.HasPrefix(input[index:], "/*"):
			end := strings.Index(input[index+2:], "*/")
			if end < 0 {
				return -1
			}
			index += end + 4
		case input[index] == '<' && index+1 < len(input) && (isIdentifierStart(input[index+1]) || input[index+1] == '.' || input[index+1] == '>') && isLikelyMarkupStart(input, index):
			return index
		default:
			index++
		}
	}
	return -1
}

func isLikelyMarkupStart(input string, start int) bool {
	previous := previousNonSpace(input, start-1)
	if previous < 0 {
		return true
	}

	switch input[previous] {
	case '(', '=', ',', ':':
		return true
	}

	wordEnd := previous + 1
	wordStart := wordEnd
	for wordStart > 0 && (unicode.IsLetter(rune(input[wordStart-1])) || input[wordStart-1] == '_') {
		wordStart--
	}
	return input[wordStart:wordEnd] == "return"
}

func skipGoQuoted(input string, start int) int {
	quote := input[start]
	index := start + 1
	for index < len(input) {
		if quote != '`' && input[index] == '\\' {
			index += 2
			continue
		}
		if input[index] == quote {
			return index + 1
		}
		index++
	}
	return len(input)
}

func unwrapReturnParentheses(input string, start, end int) (int, int) {
	open := previousNonSpace(input, start-1)
	close := nextNonSpace(input, end)
	if open < 0 || close < 0 || input[open] != '(' || input[close] != ')' {
		return start, end
	}

	wordEnd := previousNonSpace(input, open-1) + 1
	wordStart := wordEnd
	for wordStart > 0 && (unicode.IsLetter(rune(input[wordStart-1])) || input[wordStart-1] == '_') {
		wordStart--
	}
	if input[wordStart:wordEnd] != "return" {
		return start, end
	}
	return open, close + 1
}

func previousNonSpace(input string, from int) int {
	for index := from; index >= 0; index-- {
		if !unicode.IsSpace(rune(input[index])) {
			return index
		}
	}
	return -1
}

func nextNonSpace(input string, from int) int {
	for index := from; index < len(input); index++ {
		if !unicode.IsSpace(rune(input[index])) {
			return index
		}
	}
	return -1
}

func packageNameFromSource(input string) string {
	for _, line := range strings.Split(input, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "package ") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 && validGoIdentifier(fields[1]) {
			return fields[1]
		}
	}
	return "main"
}

func importAliasesFromSource(filename, input string) (map[string]string, map[string]string) {
	aliases := map[string]string{}
	invalid := map[string]string{}
	file, err := parser.ParseFile(gotoken.NewFileSet(), filename, input, parser.ImportsOnly)
	if err != nil {
		return aliases, invalid
	}
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil || importPath == "" {
			continue
		}
		if spec.Name != nil {
			alias := spec.Name.Name
			if alias == "_" || alias == "." {
				invalid[alias] = importPath
				continue
			}
			if validGoIdentifier(alias) {
				aliases[alias] = importPath
			}
			continue
		}
		alias := pathpkg.Base(importPath)
		if validGoIdentifier(alias) {
			aliases[alias] = importPath
		}
	}
	return aliases, invalid
}

func insertGeneratedDeclarations(input string, declarations string) string {
	position := declarationInsertionPoint(input)
	return input[:position] + "\n" + declarations + input[position:]
}

func declarationInsertionPoint(input string) int {
	packageIndex := strings.Index(input, "package ")
	if packageIndex < 0 {
		return 0
	}
	packageLineEnd := strings.IndexByte(input[packageIndex:], '\n')
	if packageLineEnd < 0 {
		return len(input)
	}
	position := packageIndex + packageLineEnd + 1
	importStart := skipWhitespace(input, position)
	if !strings.HasPrefix(input[importStart:], "import") || !isKeywordBoundary(input, importStart+len("import")) {
		return position
	}

	index := skipWhitespace(input, importStart+len("import"))
	if index >= len(input) {
		return len(input)
	}
	if input[index] == '(' {
		depth := 0
		for index < len(input) {
			switch input[index] {
			case '(':
				depth++
			case ')':
				depth--
				if depth == 0 {
					index++
					return lineEnd(input, index)
				}
			}
			index++
		}
		return len(input)
	}
	return lineEnd(input, index)
}

func skipWhitespace(input string, index int) int {
	for index < len(input) && unicode.IsSpace(rune(input[index])) {
		index++
	}
	return index
}

func isKeywordBoundary(input string, index int) bool {
	if index >= len(input) {
		return true
	}
	character := rune(input[index])
	return !unicode.IsLetter(character) && !unicode.IsDigit(character) && character != '_'
}

func lineEnd(input string, index int) int {
	for index < len(input) && input[index] != '\n' {
		index++
	}
	if index < len(input) {
		index++
	}
	return index
}
