package gox

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	gotoken "go/token"
	"os"
	pathpkg "path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const generatedHeader = "// Code generated by goxc; DO NOT EDIT.\n\n"

// GenerateOptions configures GOX generation.
type GenerateOptions struct {
	// Filename is used in diagnostics and generated component variable names.
	Filename string
	// PackageIdentity is the component identity prefix for generated component
	// types. When empty, generation falls back to the Go package name from the
	// source file.
	PackageIdentity string
}

// PackageSource is one source file participating in package generation.
type PackageSource struct {
	Filename string
	Source   []byte
}

// PackageGenerateOptions configures coordinated generation for one Go package.
type PackageGenerateOptions struct {
	PackageIdentity string
	AuthoredSources []PackageSource
}

// Generate transpiles all GOX element roots in a Go-like source file.
func Generate(source []byte) ([]byte, error) {
	return GenerateNamed("gox", source)
}

// GenerateNamed transpiles GOX source and includes filename in diagnostics.
func GenerateNamed(filename string, source []byte) ([]byte, error) {
	return GenerateWithOptions(source, GenerateOptions{Filename: filename})
}

// GenerateWithOptions transpiles GOX source using explicit generation options.
func GenerateWithOptions(source []byte, options GenerateOptions) ([]byte, error) {
	if options.Filename == "" {
		options.Filename = "gox"
	}
	generated, err := generatePackageSources([]generationSource{{
		PackageSource: PackageSource{Filename: options.Filename, Source: source},
		options:       options,
	}}, nil)
	if err != nil {
		return nil, err
	}
	return generated[options.Filename], nil
}

// GeneratePackageWithOptions transpiles all GOX sources in one Go package
// using one package-level generated-identifier allocation.
func GeneratePackageWithOptions(sources []PackageSource, options PackageGenerateOptions) (map[string][]byte, error) {
	packageSources := make([]generationSource, 0, len(sources))
	for _, source := range sources {
		if source.Filename == "" {
			return nil, fmt.Errorf("gox: package source filename is required")
		}
		packageSources = append(packageSources, generationSource{
			PackageSource: source,
			options: GenerateOptions{
				Filename:        source.Filename,
				PackageIdentity: options.PackageIdentity,
			},
		})
	}
	return generatePackageSources(packageSources, options.AuthoredSources)
}

type generationSource struct {
	PackageSource
	options GenerateOptions
}

type generationPlan struct {
	filename          string
	input             string
	componentIdentity string
	aliases           map[string]string
	invalidAliases    map[string]string
	discovery         *codegenContext
	packageName       string
}

func generatePackageSources(sources []generationSource, authoredSources []PackageSource) (map[string][]byte, error) {
	ordered := append([]generationSource(nil), sources...)
	sort.Slice(ordered, func(left, right int) bool {
		return ordered[left].Filename < ordered[right].Filename
	})
	for index := 1; index < len(ordered); index++ {
		if ordered[index-1].Filename == ordered[index].Filename {
			return nil, fmt.Errorf("gox: duplicate package source filename %q", ordered[index].Filename)
		}
	}

	plans := make([]generationPlan, 0, len(ordered))
	contexts := make([]*codegenContext, 0, len(ordered))
	reserved := make(map[string]struct{})
	packageName := ""
	for _, source := range ordered {
		plan, identifiers, err := prepareGenerationPlan(source)
		if err != nil {
			return nil, err
		}
		if packageName == "" {
			packageName = plan.packageName
		} else if plan.packageName != packageName {
			return nil, fmt.Errorf("%s: package %s does not match package %s", plan.filename, plan.packageName, packageName)
		}
		for identifier := range identifiers {
			reserved[identifier] = struct{}{}
		}
		plans = append(plans, plan)
		contexts = append(contexts, plan.discovery)
	}

	authored := append([]PackageSource(nil), authoredSources...)
	sort.Slice(authored, func(left, right int) bool {
		return authored[left].Filename < authored[right].Filename
	})
	for _, source := range authored {
		authoredPackage, identifiers, err := packageLevelIdentifiers(source.Filename, string(source.Source))
		if err != nil {
			return nil, err
		}
		if authoredPackage != packageName {
			continue
		}
		for identifier := range identifiers {
			reserved[identifier] = struct{}{}
		}
	}

	allocated := allocateComponentIdentifiers(contexts, reserved)
	generated := make(map[string][]byte, len(plans))
	for index, plan := range plans {
		output, err := renderGenerationPlan(plan, allocated[index])
		if err != nil {
			return nil, err
		}
		generated[plan.filename] = output
	}
	return generated, nil
}

func prepareGenerationPlan(source generationSource) (generationPlan, map[string]struct{}, error) {
	input := string(source.Source)
	componentIdentity := source.options.PackageIdentity
	if componentIdentity == "" {
		componentIdentity = packageNameFromSource(input)
	}
	aliases, invalidAliases := importAliasesFromSource(source.Filename, input)
	discovery := newCodegenContext(componentIdentity, source.Filename, true)
	discovery.withImportAliases(aliases, invalidAliases)
	generatedSource, generated, err := lowerGOXSource(input, source.Filename, discovery)
	if err != nil {
		return generationPlan{}, nil, err
	}
	if generated == 0 {
		return generationPlan{}, nil, fmt.Errorf("%s: no GOX markup elements found", source.Filename)
	}
	packageName, identifiers, err := packageLevelIdentifiers(source.Filename, generatedSource)
	if err != nil {
		return generationPlan{}, nil, err
	}
	return generationPlan{
		filename:          source.Filename,
		input:             input,
		componentIdentity: componentIdentity,
		aliases:           aliases,
		invalidAliases:    invalidAliases,
		discovery:         discovery,
		packageName:       packageName,
	}, identifiers, nil
}

func renderGenerationPlan(plan generationPlan, identifiers map[string]string) ([]byte, error) {
	ctx := newCodegenContext(plan.componentIdentity, plan.filename, true)
	ctx.withImportAliases(plan.aliases, plan.invalidAliases)
	ctx.withComponentIdentifiers(identifiers)
	generatedSource, generated, err := lowerGOXSource(plan.input, plan.filename, ctx)
	if err != nil {
		return nil, err
	}
	if generated == 0 {
		return nil, fmt.Errorf("%s: no GOX markup elements found", plan.filename)
	}
	if declarations := ctx.declarations(); declarations != "" {
		inserted, err := insertGeneratedDeclarations(plan.filename, generatedSource, declarations)
		if err != nil {
			return nil, err
		}
		generatedSource = inserted
	}

	formatted, err := format.Source(append([]byte(generatedHeader), []byte(generatedSource)...))
	if err != nil {
		return nil, fmt.Errorf("%s: generated Go source is invalid: %w", plan.filename, err)
	}
	return formatted, nil
}

func lowerGOXSource(input, filename string, ctx *codegenContext) (string, int, error) {
	var output bytes.Buffer
	cursor := 0
	searchFrom := 0
	generated := 0

	for {
		start := findMarkupStart(input, searchFrom)
		if start < 0 {
			break
		}

		line, column := lineColumn(input, start)
		element, consumed, positions, err := parseElementAtWithPositions(input[start:], filename, line, column)
		if err != nil {
			return "", 0, err
		}
		ctx.withDiagnostics(filename, input[start:], line, column, positions)
		code, err := ctx.codegen(element)
		if err != nil {
			if _, ok := asDiagnosticError(err); ok {
				return "", 0, err
			}
			return "", 0, diagnosticError(filename, line, column, err.Error(), sourceLine(input, start))
		}

		replaceStart, replaceEnd := unwrapReturnParentheses(input, start, start+consumed)
		output.WriteString(input[cursor:replaceStart])
		output.WriteString(code)
		cursor = replaceEnd
		searchFrom = replaceEnd
		generated++
	}
	output.WriteString(input[cursor:])
	return output.String(), generated, nil
}

// GenerateFile writes a .gox.go file next to the source .gox file.
func GenerateFile(path string) (string, error) {
	outputPath := path + ".go"
	return GenerateFileTo(path, outputPath)
}

// GenerateFileTo writes generated Go for a .gox file to outputPath.
func GenerateFileTo(path, outputPath string) (string, error) {
	return GenerateFileToWithOptions(path, outputPath, GenerateOptions{Filename: path})
}

// GenerateFileToWithOptions writes generated Go for a .gox file to outputPath.
func GenerateFileToWithOptions(path, outputPath string, options GenerateOptions) (string, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if options.Filename == "" {
		options.Filename = path
	}
	generated, err := GenerateWithOptions(source, options)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", fmt.Errorf("create generated directory for %s: %w", outputPath, err)
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", outputPath, err)
	}
	return outputPath, nil
}

// FindFiles returns .gox files below path in stable order.
func FindFiles(path string) ([]string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		if filepath.Ext(path) != ".gox" {
			return nil, fmt.Errorf("%s is not a .gox file", path)
		}
		return []string{path}, nil
	}

	var files []string
	err = filepath.WalkDir(path, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && filepath.Ext(path) == ".gox" {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

func findMarkupStart(input string, from int) int {
	for index := from; index < len(input); {
		switch {
		case input[index] == '"' || input[index] == '\'' || input[index] == '`':
			index = skipGoQuoted(input, index)
		case strings.HasPrefix(input[index:], "//"):
			index += 2
			for index < len(input) && input[index] != '\n' {
				index++
			}
		case strings.HasPrefix(input[index:], "/*"):
			end := strings.Index(input[index+2:], "*/")
			if end < 0 {
				return -1
			}
			index += end + 4
		case input[index] == '<' && index+1 < len(input) && (isIdentifierStart(input[index+1]) || input[index+1] == '.' || input[index+1] == '>') && isLikelyMarkupStart(input, index):
			return index
		default:
			index++
		}
	}
	return -1
}

func isLikelyMarkupStart(input string, start int) bool {
	previous := previousNonSpace(input, start-1)
	if previous < 0 {
		return true
	}

	switch input[previous] {
	case '(', '=', ',', ':':
		return true
	}

	wordEnd := previous + 1
	wordStart := wordEnd
	for wordStart > 0 && (unicode.IsLetter(rune(input[wordStart-1])) || input[wordStart-1] == '_') {
		wordStart--
	}
	return input[wordStart:wordEnd] == "return"
}

func skipGoQuoted(input string, start int) int {
	quote := input[start]
	index := start + 1
	for index < len(input) {
		if quote != '`' && input[index] == '\\' {
			index += 2
			continue
		}
		if input[index] == quote {
			return index + 1
		}
		index++
	}
	return len(input)
}

func unwrapReturnParentheses(input string, start, end int) (int, int) {
	open := previousNonSpace(input, start-1)
	close := nextNonSpace(input, end)
	if open < 0 || close < 0 || input[open] != '(' || input[close] != ')' {
		return start, end
	}

	wordEnd := previousNonSpace(input, open-1) + 1
	wordStart := wordEnd
	for wordStart > 0 && (unicode.IsLetter(rune(input[wordStart-1])) || input[wordStart-1] == '_') {
		wordStart--
	}
	if input[wordStart:wordEnd] != "return" {
		return start, end
	}
	return open, close + 1
}

func previousNonSpace(input string, from int) int {
	for index := from; index >= 0; index-- {
		if !unicode.IsSpace(rune(input[index])) {
			return index
		}
	}
	return -1
}

func nextNonSpace(input string, from int) int {
	for index := from; index < len(input); index++ {
		if !unicode.IsSpace(rune(input[index])) {
			return index
		}
	}
	return -1
}

func packageNameFromSource(input string) string {
	for _, line := range strings.Split(input, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "package ") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 && validGoIdentifier(fields[1]) {
			return fields[1]
		}
	}
	return "main"
}

func importAliasesFromSource(filename, input string) (map[string]string, map[string]string) {
	aliases := map[string]string{}
	invalid := map[string]string{}
	file, err := parser.ParseFile(gotoken.NewFileSet(), filename, input, parser.ImportsOnly)
	if err != nil {
		return aliases, invalid
	}
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil || importPath == "" {
			continue
		}
		if spec.Name != nil {
			alias := spec.Name.Name
			if alias == "_" || alias == "." {
				invalid[alias] = importPath
				continue
			}
			if validGoIdentifier(alias) {
				aliases[alias] = importPath
			}
			continue
		}
		alias := pathpkg.Base(importPath)
		if validGoIdentifier(alias) {
			aliases[alias] = importPath
		}
	}
	return aliases, invalid
}

func packageLevelIdentifiers(filename, input string) (string, map[string]struct{}, error) {
	file, err := parser.ParseFile(
		gotoken.NewFileSet(),
		filename,
		input,
		parser.ParseComments|parser.AllErrors|parser.SkipObjectResolution,
	)
	if err != nil {
		return "", nil, fmt.Errorf("%s: parse transformed Go source before generated declarations: %w", filename, err)
	}

	identifiers := make(map[string]struct{})
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			if declaration.Recv == nil {
				identifiers[declaration.Name.Name] = struct{}{}
			}
		case *ast.GenDecl:
			for _, spec := range declaration.Specs {
				switch spec := spec.(type) {
				case *ast.ValueSpec:
					for _, name := range spec.Names {
						identifiers[name.Name] = struct{}{}
					}
				case *ast.TypeSpec:
					identifiers[spec.Name.Name] = struct{}{}
				}
			}
		}
	}
	return file.Name.Name, identifiers, nil
}

func insertGeneratedDeclarations(filename, input, declarations string) (string, error) {
	fileSet := gotoken.NewFileSet()
	file, err := parser.ParseFile(
		fileSet,
		filename,
		input,
		parser.ParseComments|parser.AllErrors|parser.SkipObjectResolution,
	)
	if err != nil {
		return "", fmt.Errorf("%s: parse transformed Go source before generated declarations: %w", filename, err)
	}
	if file == nil || !file.Package.IsValid() {
		return "", fmt.Errorf("%s: parse transformed Go source before generated declarations: missing package clause", filename)
	}

	position := gotoken.NoPos
	for _, declaration := range file.Decls {
		if gen, ok := declaration.(*ast.GenDecl); ok && gen.Tok == gotoken.IMPORT {
			continue
		}
		position = declaration.Pos()
		switch declaration := declaration.(type) {
		case *ast.GenDecl:
			if declaration.Doc != nil {
				position = declaration.Doc.Pos()
			}
		case *ast.FuncDecl:
			if declaration.Doc != nil {
				position = declaration.Doc.Pos()
			}
		}
		break
	}

	offset := len(input)
	if position.IsValid() {
		tokenFile := fileSet.File(position)
		if tokenFile == nil {
			return "", fmt.Errorf("%s: locate generated declaration insertion position", filename)
		}
		offset = tokenFile.Offset(position)
	}
	return input[:offset] + "\n" + declarations + "\n" + input[offset:], nil
}
