// Code generated by goxc; DO NOT EDIT.

package main

import (
	"strings"

	gf "github.com/jin-wu/goframe/pkg/goframe"
)

type Todo struct {
	ID   int
	Text string
	Done bool
}

type HeaderProps struct {
	Title string
}

func Header(props HeaderProps) gf.Node {
	return gf.El("header", gf.Props{
		"class": "site-header",
	},
		gf.El("p", gf.Props{
			"class": "eyebrow",
		},
			gf.Text("Go-first application experiment"),
		),
		gf.El("h1", nil,
			gf.Child(props.Title),
		),
	)
}

type CardProps struct {
	Title    string
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", gf.Props{
		"class": "card",
	},
		gf.El("h2", nil,
			gf.Child(props.Title),
		),
		gf.El("div", gf.Props{
			"class": "card-body",
		},
			gf.Child(props.Children),
		),
	)
}

type ButtonProps struct {
	Label   string
	Type    string
	OnClick func()
}

type TodoFormProps struct {
	OnAdd func(value string)
}

func TodoForm(props TodoFormProps) gf.Node {
	text, setText := gf.UseState("")

	addTodo := func() {
		value := strings.TrimSpace(text)
		if value == "" {
			return
		}
		props.OnAdd(value)
		setText("")
	}

	return gf.El("form", gf.Props{
		"class": "todo-form",
		"OnSubmit": func(event gf.Event) {
			event.PreventDefault()
			addTodo()
		},
	},
		gf.El("input", gf.Props{
			"ID":          "todo-input",
			"Type":        "text",
			"Value":       text,
			"Placeholder": "What needs to be done?",
			"OnInput": func(event gf.InputEvent) {
				setText(event.Value())
			},
		},
		),
		gf.Component("Button", ButtonProps{
			Label: "Add task",
			Type:  "submit",
		}, Button),
	)
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", gf.Props{
		"class":   "button",
		"Type":    props.Type,
		"OnClick": props.OnClick,
	},
		gf.Child(props.Label),
	)
}

type EmptyStateProps struct{}

func EmptyState(props EmptyStateProps) gf.Node {
	return gf.El("div", gf.Props{
		"class": "empty-state",
	},
		gf.El("strong", nil,
			gf.Text("No tasks yet."),
		),
		gf.El("span", nil,
			gf.Text("Add the first task above."),
		),
	)
}

type TodoItemProps struct {
	Todo     Todo
	OnToggle func(id int)
	OnRemove func(id int)
}

func TodoItem(props TodoItemProps) gf.Node {
	className := "todo-item"
	status := "Mark done"
	if props.Todo.Done {
		className += " todo-item-done"
		status = "Mark active"
	}

	return gf.El("li", gf.Props{
		"ID":    "todo-" + gf.ToString(props.Todo.ID),
		"class": className,
	},
		gf.El("button", gf.Props{
			"class": "todo-toggle",
			"Type":  "button",
			"OnClick": func() {
				props.OnToggle(props.Todo.ID)
			},
		},
			gf.Child(status),
		),
		gf.El("span", gf.Props{
			"class": "todo-text",
		},
			gf.Child(props.Todo.Text),
		),
		gf.Component("Button", ButtonProps{
			Label: "Remove",
			Type:  "button",
			OnClick: func() {
				props.OnRemove(props.Todo.ID)
			},
		}, Button),
	)
}

type TodoListProps struct {
	Items    []Todo
	OnToggle func(id int)
	OnRemove func(id int)
}

func TodoList(props TodoListProps) gf.Node {
	return gf.El("ul", gf.Props{
		"ID":    "todo-list",
		"class": "todo-list",
	},
		gf.Child(gf.Map(props.Items, func(todo Todo) gf.Node {
			return gf.Key(gf.ToString(todo.ID),
				gf.Component("TodoItem", TodoItemProps{
					Todo:     todo,
					OnToggle: props.OnToggle,
					OnRemove: props.OnRemove,
				}, TodoItem),
			)
		})),
	)
}

type TodoAppProps struct{}

func TodoApp(props TodoAppProps) gf.Node {
	todos, setTodos := gf.UseState([]Todo{})
	nextID, setNextID := gf.UseState(1)

	gf.UseEffect(func() gf.Cleanup {
		if raw, ok := localStorageGet(todoStorageKey); ok {
			stored := decodeTodos(raw)
			todoSkipNextPersist = true
			setTodos(stored)
			setNextID(nextTodoID(stored))
		}
		return nil
	})

	encodedTodos := encodeTodos(todos)
	gf.UseEffect(func() gf.Cleanup {
		if todoSkipNextPersist {
			todoSkipNextPersist = false
			return nil
		}
		localStorageSet(todoStorageKey, encodedTodos)
		return nil
	}, gf.Deps(encodedTodos))

	addTodo := func(value string) {
		next := append([]Todo(nil), todos...)
		next = append(next, Todo{ID: nextID, Text: value})
		setTodos(next)
		setNextID(nextID + 1)
	}

	toggleTodo := func(id int) {
		next := make([]Todo, len(todos))
		copy(next, todos)
		for index := range next {
			if next[index].ID == id {
				next[index].Done = !next[index].Done
				break
			}
		}
		setTodos(next)
	}

	removeTodo := func(id int) {
		next := make([]Todo, 0, len(todos))
		for _, todo := range todos {
			if todo.ID != id {
				next = append(next, todo)
			}
		}
		setTodos(next)
	}

	reverseTodos := func() {
		next := make([]Todo, len(todos))
		for index := range todos {
			next[len(todos)-1-index] = todos[index]
		}
		setTodos(next)
	}

	return gf.El("main", gf.Props{
		"class": "page",
	},
		gf.Component("Card", CardProps{
			Title: "New task",
			Children: []gf.Node{
				gf.Component("TodoForm", TodoFormProps{
					OnAdd: addTodo,
				}, TodoForm),
			},
		}, Card),
		gf.Component("Card", CardProps{
			Title: "Tasks",
			Children: []gf.Node{
				gf.If((len(todos) > 0), gf.El("p", gf.Props{
					"class": "summary",
				},
					gf.Child(len(todos)),
					gf.Text(" task(s)"),
				)),
				gf.If((len(todos) > 1), gf.Component("Button", ButtonProps{
					Label:   "Reverse tasks",
					Type:    "button",
					OnClick: reverseTodos,
				}, Button)),
				gf.IfElse((len(todos) == 0), gf.Component("EmptyState", EmptyStateProps{}, EmptyState), gf.Component("TodoList", TodoListProps{
					Items:    todos,
					OnToggle: toggleTodo,
					OnRemove: removeTodo,
				}, TodoList)),
			},
		}, Card),
	)
}

func App() gf.Node {
	return gf.Fragment(
		gf.Component("Header", HeaderProps{
			Title: "GoFrame Todo",
		}, Header),
		gf.Component("TodoApp", TodoAppProps{}, TodoApp),
	)
}
