// Code generated by goxc; DO NOT EDIT.

package main

import gf "github.com/jin-wu/goframe/pkg/goframe"

type HeaderProps struct {
	Title string
}

func Header(props HeaderProps) gf.Node {
	return gf.El("header", gf.Props{
		"class": "site-header",
	},
		gf.El("h1", nil,
			gf.Child(props.Title),
		),
		gf.El("p", nil,
			gf.Text("Capitalized GOX tags call typed Go components."),
		),
	)
}

type ButtonProps struct {
	Label   string
	OnClick func()
}

func Button(props ButtonProps) gf.Node {
	return gf.El("button", gf.Props{
		"class":   "button",
		"type":    "button",
		"onClick": props.OnClick,
	},
		gf.Child(props.Label),
	)
}

type CardProps struct {
	Title    string
	Children []gf.Node
}

func Card(props CardProps) gf.Node {
	return gf.El("section", gf.Props{
		"class": "card",
	},
		gf.El("h2", nil,
			gf.Child(props.Title),
		),
		gf.El("div", gf.Props{
			"class": "card-body",
		},
			gf.Child(props.Children),
		),
	)
}

func App() gf.Node {
	count, setCount := gf.UseState(0)

	return gf.Fragment(
		gf.Component("Header", HeaderProps{
			Title: "GoFrame Components Demo",
		}, Header),
		gf.El("main", gf.Props{
			"class": "page",
		},
			gf.Component("Card", CardProps{
				Title: "Counter",
				Children: []gf.Node{
					gf.El("p", nil,
						gf.Text("Current value: "),
						gf.Child(count),
					),
					gf.Component("Button", ButtonProps{
						Label: "Increment",
						OnClick: func() {
							setCount(count + 1)
						},
					}, Button),
				},
			}, Card),
		),
	)
}
