//go:build ignore

// Command html_entities_generate copies the complete HTML5 named character
// reference table from the Go standard library into goxc's private tokenizer.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"unicode/utf8"
)

func main() {
	sourcePath := filepath.Join(runtime.GOROOT(), "src", "html", "entity.go")
	parsed, err := parser.ParseFile(token.NewFileSet(), sourcePath, nil, 0)
	if err != nil {
		fatalf("parse %s: %v", sourcePath, err)
	}

	entities := make(map[string]string)
	ast.Inspect(parsed, func(node ast.Node) bool {
		literal, ok := node.(*ast.CompositeLit)
		if !ok || !isStringEntityMap(literal.Type) {
			return true
		}
		for _, element := range literal.Elts {
			pair, ok := element.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			name, ok := stringLiteral(pair.Key)
			if !ok {
				continue
			}
			value, ok := entityValue(pair.Value)
			if !ok {
				continue
			}
			entities[name] = value
		}
		return true
	})
	if len(entities) < 2000 {
		fatalf("parsed only %d HTML named character references from %s", len(entities), sourcePath)
	}

	names := make([]string, 0, len(entities))
	longest := 0
	for name := range entities {
		names = append(names, name)
		if len(name) > longest {
			longest = len(name)
		}
	}
	sort.Strings(names)

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package main")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "// htmlNamedCharacterReferences is generated from the complete HTML5 table")
	fmt.Fprintln(&output, "// in Go's src/html/entity.go (BSD-3-Clause Go standard library source),")
	fmt.Fprintln(&output, "// which tracks the WHATWG named character reference list.")
	fmt.Fprintf(&output, "const longestHTMLNamedCharacterReference = %d\n\n", longest)
	fmt.Fprintln(&output, "var htmlNamedCharacterReferences = map[string]string{")
	for _, name := range names {
		fmt.Fprintf(&output, "\t%q: %q,\n", name, entities[name])
	}
	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile("html_entities_generated.go", formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func isStringEntityMap(expression ast.Expr) bool {
	mapType, ok := expression.(*ast.MapType)
	if !ok {
		return false
	}
	key, ok := mapType.Key.(*ast.Ident)
	return ok && key.Name == "string"
}

func stringLiteral(expression ast.Expr) (string, bool) {
	literal, ok := expression.(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING {
		return "", false
	}
	value, err := strconv.Unquote(literal.Value)
	return value, err == nil
}

func entityValue(expression ast.Expr) (string, bool) {
	if literal, ok := expression.(*ast.BasicLit); ok && literal.Kind == token.CHAR {
		value, err := strconv.Unquote(literal.Value)
		return value, err == nil && utf8.RuneCountInString(value) == 1
	}
	composite, ok := expression.(*ast.CompositeLit)
	if !ok || len(composite.Elts) != 2 {
		return "", false
	}
	var value string
	for _, element := range composite.Elts {
		literal, ok := element.(*ast.BasicLit)
		if !ok || literal.Kind != token.CHAR {
			return "", false
		}
		decoded, err := strconv.Unquote(literal.Value)
		if err != nil || utf8.RuneCountInString(decoded) != 1 {
			return "", false
		}
		value += decoded
	}
	return value, true
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "html entity generation: "+format+"\n", arguments...)
	os.Exit(1)
}
